import argparse
import csv
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill, Side, Border


DEFAULT_CSV = Path(r"E:\Data\USD\procedure\uav_usd_xform_joint_counts.csv")
DEFAULT_SUMMARY = Path(r"E:\Data\USD\procedure\uav_usd_xform_joint_counts.xlsx")
DEFAULT_UAV_ROOT = Path(r"E:\SoftAPP\Isaac-Plugin\UAV\UAV")
DELIVERY_HEADERS = [
    "物体名称",
    "是否包含可活动零件",
    "零件数量",
    "关节数量",
    "包含残缺零件的数量（没有请填0）",
]


def parse_args():
    parser = argparse.ArgumentParser(description="Create XLSX review workbooks from USD statistics CSV.")
    parser.add_argument("--csv", default=str(DEFAULT_CSV), help="Input CSV generated by count_usd_xforms.py.")
    parser.add_argument("--summary", default=str(DEFAULT_SUMMARY), help="Summary XLSX output path.")
    parser.add_argument(
        "--per-folder",
        action="store_true",
        help="Also write one workbook next to each USD folder as <folder>.xlsx.",
    )
    parser.add_argument(
        "--delivery-per-folder",
        action="store_true",
        help="Write per-folder workbooks in the same 5-column delivery format as E:\\Data\\USD\\kook.",
    )
    parser.add_argument(
        "--folder-root",
        default=str(DEFAULT_UAV_ROOT),
        help="Root folder that contains one subfolder per USD.",
    )
    parser.add_argument(
        "--object-name",
        default="无人机",
        help="Object name written to A2 in delivery-format workbooks.",
    )
    return parser.parse_args()


def read_rows(csv_path: Path):
    with csv_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        return list(csv.reader(csv_file))


def style_sheet(ws):
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    thin = Side(style="thin", color="B7B7B7")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for row in ws.iter_rows():
        for cell in row:
            cell.border = border
            cell.alignment = Alignment(vertical="center", wrap_text=True)

    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    ws.row_dimensions[1].height = 36

    for column_cells in ws.columns:
        column_letter = column_cells[0].column_letter
        max_length = 0
        for cell in column_cells:
            value = "" if cell.value is None else str(cell.value)
            max_length = max(max_length, len(value))
        ws.column_dimensions[column_letter].width = min(max(max_length + 2, 10), 32)


def save_table(headers, rows, output_path: Path, title=None):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "USD审查"

    ws.append(headers)
    for row in rows:
        ws.append(row)

    style_sheet(ws)

    if title:
        ws.sheet_view.showGridLines = False

    wb.save(output_path)
    return output_path


def make_per_folder_workbooks(headers, rows):
    written = 0
    skipped = 0
    folder_index = headers.index("文件夹")
    relative_index = headers.index("相对路径")

    for row in rows:
        relative_path = Path(row[relative_index])
        if len(relative_path.parts) < 2:
            skipped += 1
            continue

        folder_path = Path(r"E:\SoftAPP\Isaac-Plugin\UAV\UAV") / row[folder_index]
        output_path = folder_path / f"{row[folder_index]}.xlsx"
        save_table(headers, [row], output_path)
        written += 1

    return written, skipped


def write_delivery_workbook(output_path: Path, object_name, part_count, joint_count):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "Sheet1"

    for col, header in enumerate(DELIVERY_HEADERS, start=1):
        ws.cell(1, col).value = header
        ws.column_dimensions[ws.cell(1, col).column_letter].width = 13

    ws["A2"].value = object_name
    ws["B2"].value = "是" if int(joint_count or 0) > 0 else "否"
    ws["C2"].value = int(part_count or 0)
    ws["D2"].value = int(joint_count or 0)
    ws["E2"].value = 0

    wb.create_sheet("Sheet2")
    wb.create_sheet("Sheet3")
    wb.save(output_path)
    return output_path


def make_delivery_per_folder_workbooks(headers, rows, folder_root: Path, object_name):
    written = 0
    skipped = 0
    folder_index = headers.index("文件夹")
    part_index = headers.index("非group*且非根Xform数量")
    joint_index = headers.index("USD关节数量")

    for row in rows:
        folder_name = row[folder_index]
        folder_path = folder_root / folder_name
        if not folder_path.exists() or not folder_path.is_dir():
            skipped += 1
            continue

        output_path = folder_path / f"{folder_name}.xlsx"
        try:
            write_delivery_workbook(
            output_path,
            object_name=object_name,
            part_count=row[part_index],
            joint_count=row[joint_index],
        )
            written += 1
        except PermissionError:
            print(f"Locked workbook, skipped: {output_path}")
            skipped += 1

    return written, skipped


def main():
    args = parse_args()
    rows = read_rows(Path(args.csv))
    if not rows:
        raise SystemExit("CSV is empty.")

    headers = rows[0]
    body = rows[1:]

    summary_path = save_table(headers, body, Path(args.summary))
    print(f"Summary XLSX: {summary_path}")

    if args.per_folder:
        written, skipped = make_per_folder_workbooks(headers, body)
        print(f"Per-folder XLSX written: {written}")
        print(f"Skipped: {skipped}")

    if args.delivery_per_folder:
        written, skipped = make_delivery_per_folder_workbooks(
            headers,
            body,
            Path(args.folder_root),
            args.object_name,
        )
        print(f"Delivery-format per-folder XLSX written: {written}")
        print(f"Skipped: {skipped}")


if __name__ == "__main__":
    main()
